//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplooyes_tbl
    {
        public int emplooye_id { get; set; }
        public int company_employee_id { get; set; }
        public System.DateTime start_work_date { get; set; }
        public System.DateTime end_work_date { get; set; }
        public string emplooye_name { get; set; }
    
        public virtual company_tbl company_tbl { get; set; }
    }
}
